const fs = require('fs');
const path = require('path');

const localesPath = path.join(__dirname, '../public/locales');

const translations = {
  en: {
    "invoice_title": "INVOICE",
    "invoice_no_label": "Invoice No",
    "issue_date_label": "Issue Date",
    "due_date_label": "Due Date",
    "bill_to_label": "Billed To",
    "bill_from_label": "From",
    "tax_id_label": "Tax ID:",
    "description_header": "Description",
    "price_header": "Price",
    "qty_header": "Qty",
    "total_header": "Total",
    "payment_label": "Payment Instructions",
    "terms_conditions_label": "Notes & Terms",
    "subtotal_label": "Subtotal",
    "discount_label": "Discount",
    "tax_label": "Tax",
    "shipping_label": "Shipping",
    "paid_label": "Amount Paid",
    "total_label": "Balance Due",
    "header.history": "History",
    "header.guides": "Guides",
    "header.signIn": "Sign In",
    "header.signUp": "Sign Up"
  },
  es: {
    "invoice_title": "FACTURA",
    "invoice_no_label": "Nº Factura",
    "issue_date_label": "Fecha Emisión",
    "due_date_label": "Vencimiento",
    "bill_to_label": "Facturar a",
    "bill_from_label": "De",
    "tax_id_label": "NIF/CIF:",
    "description_header": "Descripción",
    "price_header": "Precio",
    "qty_header": "Cant.",
    "total_header": "Total",
    "payment_label": "Instrucciones de Pago",
    "terms_conditions_label": "Notas y Condiciones",
    "subtotal_label": "Subtotal",
    "discount_label": "Descuento",
    "tax_label": "Impuestos",
    "shipping_label": "Envío",
    "paid_label": "Monto Pagado",
    "total_label": "Saldo Pendiente",
    "header.history": "Historial",
    "header.guides": "Guías",
    "header.signIn": "Entrar",
    "header.signUp": "Registro"
  },
  fr: {
    "invoice_title": "FACTURE",
    "invoice_no_label": "Nº Facture",
    "issue_date_label": "Date d'émission",
    "due_date_label": "Date d'échéance",
    "bill_to_label": "Facturer à",
    "bill_from_label": "De",
    "tax_id_label": "TVA:",
    "description_header": "Description",
    "price_header": "Prix",
    "qty_header": "Qté",
    "total_header": "Total",
    "payment_label": "Instructions de Paiement",
    "terms_conditions_label": "Notes & Conditions",
    "subtotal_label": "Sous-total",
    "discount_label": "Remise",
    "tax_label": "Taxes",
    "shipping_label": "Livraison",
    "paid_label": "Montant Payé",
    "total_label": "Solde Dû",
    "header.history": "Historique",
    "header.guides": "Guides",
    "header.signIn": "Se connecter",
    "header.signUp": "S'inscrire"
  },
  de: {
    "invoice_title": "RECHNUNG",
    "invoice_no_label": "Rechnungs-Nr",
    "issue_date_label": "Rechnungsdatum",
    "due_date_label": "Fälligkeitsdatum",
    "bill_to_label": "Rechnung an",
    "bill_from_label": "Von",
    "tax_id_label": "Steuer-Nr:",
    "description_header": "Beschreibung",
    "price_header": "Preis",
    "qty_header": "Menge",
    "total_header": "Gesamt",
    "payment_label": "Zahlungsanweisungen",
    "terms_conditions_label": "Hinweise & Bedingungen",
    "subtotal_label": "Zwischensumme",
    "discount_label": "Rabatt",
    "tax_label": "Steuer",
    "shipping_label": "Versand",
    "paid_label": "Bezahlter Betrag",
    "total_label": "Fälliger Betrag",
    "header.history": "Verlauf",
    "header.guides": "Anleitungen",
    "header.signIn": "Anmelden",
    "header.signUp": "Registrieren"
  },
  pt: {
    "invoice_title": "FATURA",
    "invoice_no_label": "Nº Fatura",
    "issue_date_label": "Data Emissão",
    "due_date_label": "Vencimento",
    "bill_to_label": "Faturar a",
    "bill_from_label": "De",
    "tax_id_label": "NIF/CNPJ:",
    "description_header": "Descrição",
    "price_header": "Preço",
    "qty_header": "Qtd",
    "total_header": "Total",
    "payment_label": "Instruções de Pagamento",
    "terms_conditions_label": "Notas e Termos",
    "subtotal_label": "Subtotal",
    "discount_label": "Desconto",
    "tax_label": "Imposto",
    "shipping_label": "Frete",
    "paid_label": "Valor Pago",
    "total_label": "Saldo Devedor",
    "header.history": "Histórico",
    "header.guides": "Guias",
    "header.signIn": "Entrar",
    "header.signUp": "Inscrever-se"
  },
  bn: {
    "invoice_title": "ইনভয়েস",
    "invoice_no_label": "ইনভয়েস নম্বর",
    "issue_date_label": "ইস্যুর তারিখ",
    "due_date_label": "শেষ তারিখ",
    "bill_to_label": "যাকে বিল করা হবে",
    "bill_from_label": "প্রেরক",
    "tax_id_label": "ট্যাক্স আইডি:",
    "description_header": "বিবরণ",
    "price_header": "মূল্য",
    "qty_header": "পরিমাণ",
    "total_header": "মোট",
    "payment_label": "পেমেন্ট নির্দেশিকা",
    "terms_conditions_label": "নোট ও শর্তাবলী",
    "subtotal_label": "উপমোট",
    "discount_label": "ছাড়",
    "tax_label": "ট্যাক্স",
    "shipping_label": "শিপিং",
    "paid_label": "প্রদত্ত পরিমাণ",
    "total_label": "বকেয়া",
    "header.history": "হিস্ট্রি",
    "header.guides": "গাইড",
    "header.signIn": "লগ ইন",
    "header.signUp": "সাইন আপ"
  },
  ar: {
    "invoice_title": "فاتورة",
    "invoice_no_label": "رقم الفاتورة",
    "issue_date_label": "تاريخ الإصدار",
    "due_date_label": "تاريخ الاستحقاق",
    "bill_to_label": "فاتورة إلى",
    "bill_from_label": "من",
    "tax_id_label": "الرقم الضريبي:",
    "description_header": "الوصف",
    "price_header": "السعر",
    "qty_header": "الكمية",
    "total_header": "الإجمالي",
    "payment_label": "تعليمات الدفع",
    "terms_conditions_label": "الملاحظات والشروط",
    "subtotal_label": "المجموع الفرعي",
    "discount_label": "خصم",
    "tax_label": "ضريبة",
    "shipping_label": "شحن",
    "paid_label": "المبلغ المدفوع",
    "total_label": "الرصيد المستحق",
    "header.history": "السجل",
    "header.guides": "أدلة",
    "header.signIn": "دخول",
    "header.signUp": "تسجيل"
  }
};

Object.keys(translations).forEach(lang => {
  const dirPath = path.join(localesPath, lang);
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
  const filePath = path.join(dirPath, 'translation.json');
  fs.writeFileSync(filePath, JSON.stringify(translations[lang], null, 2), 'utf-8');
  console.log(`Updated translation for ${lang}`);
});
